version: "3"

services:
  web:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - docroot:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: .
    volumes:
      - docroot:/var/www/html
      - ./hako-init.php:/var/www/html/hako-init.php
      - ./data:/data

volumes:
  docroot: